
export const titleInfo: Weaponse[] = [
  {
    id: 0,
    Type: "Type",
    Name: "Name",
    SubType: "SubType",
    Weapon: "Weapon",
    Accuracy: "Accuracy",
    Damage: "Damage",
    Range: "Range",
    FireRate: "FireRate",
    Mobility: "Mobility",
    Control: "Control",
    Pros: "Pros",
  },
]

export const attachments: Weaponse[] = [
  {
    id: 1,
    Type: "Mod",
    Name: "Breacher Device",
    SubType: "Muzzle",
    Weapon: 725,
    Accuracy: 0,
    Damage: 0,
    Range: 0,
    FireRate: 0,
    Mobility: -6,
    Control: -7,
    Pros: "Melee Quickness",
  },
  {
    id: 2,
    Type: "Mod",
    Name: "Sawed-Off Barrel",
    SubType: "Barrel",
    Weapon: 725,
    Accuracy: -4,
    Damage: 6,
    Range: -11,
    FireRate: 0,
    Mobility: 13,
    Control: -3,
    Pros: "Aim Down Sight Speed - Movement Speed - Wider Pellet Spread",
  },
  {
    id: 3,
    Type: "Mod",
    Name: "Tempus 32\" Competition",
    SubType: "Barrel",
    Weapon: 725,
    Accuracy: 4,
    Damage: -2,
    Range: 6,
    FireRate: 0,
    Mobility: -4,
    Control: -5,
    Pros: "Damage Range - Tighter Pellet Spread",
  },
  {
    id: 4,
    Type: "Mod",
    Name: "1Mw Laser",
    SubType: "Laser",
    Weapon: 725,
    Accuracy: 0,
    Damage: 0,
    Range: 0,
    FireRate: 0,
    Mobility: 3,
    Control: -3,
    Pros: "Sprint to Fire Speed",
  },
  {
    id: 5,
    Type: "Mod",
    Name: "5Mw Laser",
    SubType: "Laser",
    Weapon: 725,
    Accuracy: 3,
    Damage: 0,
    Range: 0,
    FireRate: 0,
    Mobility: 7,
    Control: -3,
    Pros: "Hip Fire Accuracy - Sprint to Fire Speed",
  },
  {
    id: 6,
    Type: "Mod",
    Name: "Tac Laser",
    SubType: "Laser",
    Weapon: 725,
    Accuracy: 6,
    Damage: 0,
    Range: 0,
    FireRate: 0,
    Mobility: 11,
    Control: 0,
    Pros: "Aim Down Sight Speed - Aiming Stability - ianalking saadinas",
  },
];
